// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJTxtJvaRajeOtCQGkJ66423Gwhh-pZ3g',
    appId: '1:235467762240:web:bf5afcf7515cb12f33cda5',
    messagingSenderId: '235467762240',
    projectId: 'sf221-3d822',
    authDomain: 'sf221-3d822.firebaseapp.com',
    storageBucket: 'sf221-3d822.appspot.com',
    measurementId: 'G-F9EJWZX1PG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZhx7veZkgFsxx8H7XwQS79Db4g7KvKGI',
    appId: '1:235467762240:android:d6f3269009c29c0433cda5',
    messagingSenderId: '235467762240',
    projectId: 'sf221-3d822',
    storageBucket: 'sf221-3d822.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8Lim_Hqp45XS-2h7jZko2BDnB8oZNEy4',
    appId: '1:235467762240:ios:b138727cb868fa7b33cda5',
    messagingSenderId: '235467762240',
    projectId: 'sf221-3d822',
    storageBucket: 'sf221-3d822.appspot.com',
    iosClientId: '235467762240-n38dlp3bdo1lghl7jrs7p0gjv9og5rrq.apps.googleusercontent.com',
    iosBundleId: 'com.example.sf221',
  );
}
